services:
  - type: worker
    name: queue
    region: ohio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A app:celery_app worker --loglevel=INFO --concurrency=2"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
  
  - type: web
    name: app
    region: ohio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:server"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
  - type: web
    name: flower
    region: ohio
    plan: free
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery flower --app tasks --loglevel info"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: celery-redis
          property: connectionString
  - type: redis
    name: celery-redis
    region: ohio
    plan: starter # we choose a plan with persistence to ensure tasks are not lost upon restart
    maxmemoryPolicy: noeviction
    ipAllowList: [] # only allow internal connections